on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
      

    steps: 
      - name: 'Before'
        run: echo marwan

      - uses: actions/checkout@v3 

      - name: 'After'
        run: echo marwan

